server:
  port: 8080

api:
  path: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      discovery:
        locator:
          enabled: false
      routes:
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=${api.path}/applications/**
        - id: audit-storage-service-audit
          uri: lb://audit-storage-service
          predicates:
            - Path=/api/audit/**
        - id: audit-storage-service-storage
          uri: lb://audit-storage-service
          predicates:
            - Path=/api/storage/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}