server:
  port: ${PORT:8081}

spring:
  application:
    name: auth-service
#    database connection string
  datasource:
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:2}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST:nicdbpgs.postgres.database.azure.com}:${PGPORT:5432}/${PGDATABASE:auth_db}?sslmode=require}
    username: ${PGUSER:pguser}
    password: ${PGPASSWORD:NicDB@123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  rabbitmq:
    host: ${RABBITMQ_HOST:toucan.lmq.cloudamqp.com}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:nnmhsfhw}
    password: ${RABBITMQ_PASSWORD:cIpl_gm0K2QxsPS-bp51PHpD2aojyuS7}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:nnmhsfhw}

app:
  jwt:
    secret: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-milliseconds: 86400000
  admin:
    default-username: ${ADMIN_DEFAULT_USER:admin}
    default-password: ${ADMIN_DEFAULT_PASS:admin@123}
    default-email: ${ADMIN_DEFAULT_EMAIL:prasadkvithana@gmail.com}
  otp:
    expiration-minutes: 5
  frontend:
    url: ${FRONTEND_URL:https://wonderful-wave-0320abf00.3.azurestaticapps.net}
  reset-password:
    expiration-minutes: 15
    frontend-url: ${FRONTEND_RESET_PASSWORD_URL:${app.frontend.url}/reset-password}
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:notification.exchange}
    routing-key: ${RABBITMQ_ROUTING_KEY:notification.update}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,https://*.azurecontainerapps.io,https://*.azurestaticapps.net}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

#springdoc:
#  api-docs:
#    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    rabbit:
      enabled: ${MANAGEMENT_HEALTH_RABBIT_ENABLED:false}

