server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: platform-management-service
  config:
    import: optional:file:.env[.properties]

  datasource:
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:2}
    url: ${DB_URL:jdbc:postgresql://${PGHOST:nicdbpgs.postgres.database.azure.com}:${PGPORT:5432}/${PGDATABASE:platform_management_db}?sslmode=require}
    username: ${PGUSER:pguser}
    password: ${PGPASSWORD:NicDB@123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
    host: ${RABBITMQ_HOST:toucan.lmq.cloudamqp.com}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:nnmhsfhw}
    password: ${RABBITMQ_PASSWORD:cIpl_gm0K2QxsPS-bp51PHpD2aojyuS7}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:nnmhsfhw}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    rabbit:
      enabled: ${MANAGEMENT_HEALTH_RABBIT_ENABLED:false}

logging:
  level:
    com.portal.platformservice: INFO
    com.zaxxer.hikari: DEBUG