ALTER TABLE resumes ADD COLUMN IF NOT EXISTS title VARCHAR(150);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS file_size VARCHAR(50);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS target_role VARCHAR(100);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS storage_file_id VARCHAR(100);
