ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS headline VARCHAR(255);
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(255);
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS github_url VARCHAR(255);
