server:
  port: 8084

spring:
  application:
    name: application-service
  datasource:
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:2}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST:nicdbpgs.postgres.database.azure.com}:${PGPORT:5432}/${PGDATABASE:application_service_db}?sslmode=require}
    username: ${PGUSER:pguser}
    password: ${PGPASSWORD:NicDB@123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:toucan.lmq.cloudamqp.com}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:nnmhsfhw}
    password: ${RABBITMQ_PASSWORD:cIpl_gm0K2QxsPS-bp51PHpD2aojyuS7}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:nnmhsfhw}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    rabbit:
      enabled: ${MANAGEMENT_HEALTH_RABBIT_ENABLED:false}

ai-service:
  url: ${AI_SERVICE_URL:http://localhost:8000}

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8081}

vacancy-service:
  url: ${VACANCY_SERVICE_URL:http://localhost:8087}


