package com.nsbm.authservice.entity;

public enum Role {
    SYSTEM_ADMIN,
    FACULTY_MANAGEMENT,
    FACULTY_COORDINATOR,
    INTERNSHIP_COORDINATOR,
    EVENT_COORDINATOR,
    ADMINISTRATIVE_STAFF,
    GUEST_SPEAKER,
    STUDENT,
    INDUSTRY_PARTNER
}