name: Application Service Pipeline

on:
  push:
    branches: ["feature/application-service"]
    paths:
      - "services/application-service/**"
      - "pom.xml"
  pull_request:
    branches: ["main"]
    paths:
      - "services/application-service/**"
      - "pom.xml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v7

      - name: Install JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Give Permissions to Maven in ubuntu
        run: chmod +x mvnw

      #      to see what files are in the project folder
      - name: see files
        run: ls -la

      - name: Build & Test Application Service
        run: ./mvnw clean test -pl services/application-service -am

      - name: Package Application Service
        run: ./mvnw package -DskipTests -pl services/application-service -am

      - name: Upload Application Service Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-service-jar
          path: services/application-service/target/*.jar
