name: Notification Service Pipeline

on:
  push:
    branches: ["notification-service"]
    paths:
      - "services/notification-service/**"
      - "pom.xml"
  pull_request:
    branches: ["main"]
    paths:
      - "services/notification-service/**"
      - "pom.xml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      # - name: Give Permissions to Maven in ubuntu -- run 2
      #   run: chmod +x mvnw

      - name: see files
        run: ls -la

      - name: Build & Test Notification Service
        run: ./mvnw clean test -pl services/notification-service -am

      - name: Package Notification Service
        run: ./mvnw package -DskipTests -pl services/notification-service -am

      - name: Upload Notification Service Artifact
        uses: actions/upload-artifact@v4
        with:
          name: notification-service-jar
          path: services/notification-service/target/*.jar
